### ISSUE TITLE
Not implemented tracker

### ISSUE THREAD

**Issue by Rot127** [Rot127/rzil-compiler#12]
**Pure execs**
- [ ] `sizeof`
- [ ] `->`

**Functions**

- [ ] int128_exts64
- [ ] revbit32
- [ ] gen_store_conditional4
- [ ] gen_store_conditional8
- [ ] conv_round
- [ ] gen_vreg_load -> 57
- [x] conv_4u_to_sf
- [x] conv_4u_to_df
- [x] conv_4s_to_sf
- [ ] conv_4s_to_df
- [ ] conv_8u_to_sf
- [ ] conv_8u_to_df
- [ ] conv_8s_to_sf
- [ ] conv_8s_to_df
- [ ] ctpop64
- [ ] ctpop32
- [ ] clo64
- [ ] revbit64
- [ ] interleave
- [ ] deinterleave
- [ ] helper_raise_exception

**Macros**

- [ ] fCARRY_FROM_ADD
- [ ] fEA_BREVR
- [ ] fPM_CIRI
- [ ] fPM_CIRR
- [ ] fCARRY_FROM_ADD
- [ ] fFLOAT
- [ ] fSF_RECIP_COMMON
- [ ] fSF_INVSQRT_COMMON
- [ ] fDOUBLE

**Comment by Rot127** [comment]
Is shown when running `LLVMImporter`
