### ISSUE TITLE
Optimization tracker

### ISSUE THREAD

**Issue by Rot127** [Rot127/rzil-compiler#16]
Possible optimizations:

- [x] Reduce multiple casts to a single one, if possible. Due to the many nested macros there are regularly patterns like `((ut8)(ut32)val)`. These duplicate down casts, can be reduced to a single one.
- [x] Some arithmetic can be reduced to a single scalar value (`0 * 16` and the like).
- [x] `SEQ` of 1 can be reduced to their single effect.
- [ ] https://github.com/Rot127/rzil-compiler/issues/8
- [x] Spread instruction parsing onto multiple threads.
- [x] generate names in Pures an Effect classes to safe a parameter.
- [x] Certain QEMU macros could be compiled on there own and used as sub-routines in the rzil code. This would reduce the line count of the `il_ops` files. Also it would become way way more readable. But this needs a working and tested implementation before. 
- [x] Do not add cast if types match already
- [x] A lot of LET statements can be replaced `UN()`

**Comment by Rot127** [comment]
Last point tracked in #8
